<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HD1AB2KY78F1DTO" name="Test(failed)" tests="1" failures="1" timestamp="9 Sep 2018 07:09:55 GMT" time="8.133" errors="0">
  <testcase name="test1" time="2.482" classname="SeleniumTest.com.delta.test.Test1">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at SeleniumTest.com.delta.test.Test1.test1(Test1.java:25)
	at SeleniumTest.com.delta.test.RunTestNG.main(RunTestNG.java:27)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
</testsuite> <!-- Test(failed) -->
